openapi: 3.0.0
info:
  title: TechPit Backend
  version: 1.0.0
  description: TechPit Blog
servers:
  - url: http://localhost:8080
    description: Development server
paths:
  /post/{postId}:
    put:
      summary: Update a post
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: string
          description: The ID of the post to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
      responses:
        200:
          description: Post updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  postId:
                    type: string
                  title:
                    type: string
                  content:
                    type: string
        400:
          description: Invalid input
        404:
          description: Post not found
